spring:
  application:
    name: consumer

  cloud:
    function:
      definition: riderName;riderAge
    stream:
      function:
        definition: riderName;riderAge
      bindings:
        riderName-in-0:
          destination: my-topic
        riderAge-in-0:
          destination: my-topic-1
      kafka:
        binder:
          brokers: localhost:9092

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: '*'
#        spring.json.value.default.type: com.example.consumer.Rider
server:
  port: 8081